### ISSUE TITLE
Special Apostrophes from Mac OS X servers break code

### ISSUE THREAD

**Issue by justinrhodes** [jakewaldron/PlexEmail#25]
When someone has a server called "John's iMac" after setting up Plex on an OS X Machine, that special apostrophe for the default name is breaking the XML import for getting users emails.

The apostrophe is unicode character \u2019.

Is there anyway to add some removal tool before importing and parsing the XML? The only workaround I have had right now is removing those user's servers from my list....or asking them to change the name of their server.

**Comment by jakewaldron** [comment]
This should be fixed as of v0.7.1.  Are you seeing this issue in the current version?

**Comment by justinrhodes** [comment]
I'm running this in a docker. (https://hub.docker.com/r/linuxserver/plexemail/)

What is the best way to check version number?

**Comment by jakewaldron** [comment]
I'm not familiar with how dockers work, so I'm not sure how to verify the version you are running.  However if you can attach the plexEmail.py file I can take a look to see if it has the fix in it.

**Comment by justinrhodes** [comment]
[plexemail.txt](https://github.com/jakewaldron/PlexEmail/files/155997/plexemail.txt)

**Comment by jakewaldron** [comment]
Looks like it is updated with the latest script file.  I took a closer look and it looks like the fix in v0.7.1 had been removed in a later release.  I just checked in a new version that has the fix back in.  The docker doc says that it should update on restart of the docker.  Could you try updating and running the latest?

Otherwise, if that doesn't work, you can fix it by replacing line 298 in that file (parsed = XML(response.text)) with:

parsed = XML(response.text.encode('ascii', 'ignore'))

**Comment by justinrhodes** [comment]
Pulling the latest version on a docker restart grabbed the correct version. Sorry for the confusion, I had no idea it was already patched ;)
