### ISSUE TITLE
Email always too long

### ISSUE THREAD

**Issue by Pavestone6556** [jakewaldron/PlexEmail#37]
Gmail always errors my email for being above length because I do add quite a bit each week. 

Does the cloundinary option help with that or no?

I have tried filtering and I just can't filter enough away to make it useful yet small enough. Turning off images seems no fun as well.

**Comment by jakewaldron** [comment]
If you are attaching the images directly to the email, then this could happen.  Yes, I would suggest trying Cloudinary as it will upload the images there and then only linking to that image hosted there instead of directly to the email.  I have also found that attaching emails directly can be unreliable with some email clients/browsers.

**Comment by Pavestone6556** [comment]
Thanks for the advice!
